CREATE DATABASE application CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON application.* TO 'user'@'%' IDENTIFIED BY 'user' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON application.* TO 'user'@'localhost' IDENTIFIED BY 'user' WITH GRANT OPTION;
FLUSH PRIVILEGES;
